services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app # Volume pour synchroniser les fichiers du frontend
      - /app/node_modules
    environment:
      - NODE_ENV=development # Mode developpement active
    depends_on:
      - backend
    networks:
      - transcendance

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - transcendance

networks:
  transcendance:
    driver: bridge